### ISSUE TITLE
Can’t update to 3259

### ISSUE THREAD

**Issue by bca009** [laciba96/WinBox-for-86Box#29] opened 2021-11-15 03:03 UTC
**Before you start please read [this guide about reporting bugs.](https://github.com/laciba96/WinBox-for-86Box/wiki/Contribution-Guide#accepted-form-of-issues)**
Can’t update to 3259.

**Translation of the error message**
If the error message is not in English, a translation of the message.

**To Reproduce**
Write down how can you recreate the bug step-by-step.

While you don't know how you can consistently reproduce the bug on your PC please don't report it.

**Screenshots**
Create a screenshot with all open WinBox windows are visible.
Make sure that no user input controls are hidden with other dialog boxes, like on the image below.

![](https://raw.githubusercontent.com/laciba96/WinBox-Reloaded/main/Images/ErrorSample.PNG)

You can freely move the error dialog to a less covering position before you create the screenshot.

**Technical informations (please complete the following information):**
- OS: [e.g. Windows 10 20H2, Hungarian language and regional settings]

- WinBox for 86Box Version [e.g. v1.0.0.547]
- 86Box Version [e.g. v3.0.0.3063]
- WinBox Installation Folder: [e.g. C:\Program Files\Laci bá'\WinBox for 86Box]
- WinBox VMs Folder: [e.g. C:\Users\Test User\Documents\WinBox Virtual Machines\]
- WinBox Command Line: [e.g. -lang hu-HU]

- Selected VM folder: [e.g. C:\Users\Test User\Documents\WinBox Virtual Machines\{03085aef-88ac-4417-82d6-4a7216742e74}]
- Selected VM emulator path: [e.g. C:\Users\Test User\AppData\Roaming\Laci bá'\WinBox\86Box]

**Log file about the error**
If the program generates a log file during the error, please save it and upload here.

**Additional context**

**Comment by laciba96** [comment] 2021-11-15 18:45
> **Before you start please read [this guide about reporting bugs.](https://github.com/laciba96/WinBox-for-86Box/wiki/Contribution-Guide#accepted-form-of-issues)**

I understand that you've encountered an error, but next time please fill the bug report correctly, since such a report does not help me in that at all. Read the Guide (!) in the start of the report before posting next time.

Anyways the is bug is fixed with the next version, so the issue is closed.

**Closed by laciba96** 2021-11-15 18:45 UTC
Labels: bug
